### ISSUE TITLE
Rhino Issue: Cannot open Intent Editor in Picovoice Console

### ISSUE THREAD

**Issue by fengshuifever** [Picovoice/rhino#91] opened 2021-04-27 04:14 UTC
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
Click on newly created Rhino Context using Empty Template, the Intent Editor displays

### Actual behaviour
Browser displays an empty page, with the following console errors
TypeError: can't convert null to object
Uncaught (in promise) TypeError: can't convert null to object

### Steps to reproduce the behaviour
Create new Rhino Context with an Empty Template and click on it to progress to Intent Editor
(Include enough details so that the issue can be reproduced independently.)
(Using Firefox Browser)

**Comment by dbartle** [comment] 2021-04-27 07:32
Thank you for the bug report and apologies for the inconvenience. There was an issue affecting blank templates and a fix has been deployed. Can you please try again and let me know if it works for you?

**Comment by kenarsa** [comment] 2021-05-05 15:51
closing due to inactivity. re-open if the issue is still there.

**Closed by kenarsa** 2021-05-05 15:51 UTC
Labels: bug
