### ISSUE TITLE
slot names cannot accept numerals 

### ISSUE THREAD

**Issue by JPCDekker** [Picovoice/rhino#278] opened 2022-01-14 14:17 UTC
Hi there,
I have been using the Picovoice console for some time now and I really like it. But since two days I get an error when I want to rebuild new context from the console. The context was created entirely in the console (I didn't change the .yaml file and uploaded it to the console). After pressing the microphone icon, the context is saved and rebuilt but then the process stops in the “WA” phase and the message “Error retrieving context” appears.

![afbeelding](https://user-images.githubusercontent.com/24541076/149521003-33b4682e-16ac-4a7f-be8f-f565f749f38e.png)

I am using Firefox but got the same with Chrome.
Also I found that I cannot use a digit anymore to indicate different slot phrases like room1 and room2 in new intents while in already existing intents the digits still work. Could this be related to the error mentioned above?

![afbeelding](https://user-images.githubusercontent.com/24541076/149524689-4537fb16-a84f-46a2-b19e-f2ba846a5599.png)

Cheers! Jeroen.

**Comment by JPCDekker** [comment] 2022-01-17 08:51
Goodmorning Pico, this morning I started a new Rhino context and imported the .yml that caused the error and guess what: there is no error when I press the mic button.... So that seems to work again. What remains is that I cannot use digits anymore.

**Comment by kenarsa** [comment] 2022-01-21 17:54
happy that this is resolved. @ErisMik can you please look into why numerics are not accepted? I thought we expanded the set of acceptable chars.

**Comment by ErisMik** [comment] 2022-01-22 00:12
The Rhino editor has been updated to allow for using numerals in `slot types` and `slot names`, please try again and let me know if the problem is resolved. I'll close this issue for now, but feel free to open another if you run into any more problems.

**Closed by ErisMik** 2022-01-22 00:12 UTC
Labels: enhancement

**Comment by JPCDekker** [comment] 2022-01-26 08:24
Goodmorning Erik, apologies for not replying sooner. I was able to try and use digits this morning and it all looks good now. I reckon you also would like to know if the problem is solved ;-). Thanks!

**Comment by ErisMik** [comment] 2022-01-26 20:22
@JPCDekker Could you export the context that results in that error as YAML and post it here?

**Comment by JPCDekker** [comment] 2022-01-28 07:02
Hi Eric, I coded a new context and tested it yesterday. But this morning I got the error again. It seems the error appears when my laptop has gone to hybernate and started back up again (though some older contexts still work properly). So it might be a browser thing (I am using Firefox) but I am no expert. Logging out of the Pico account, refreshing the page and logging in doesn't work. Please find the exported new set attached.
[MockUp VBH VoCo 3.zip](https://github.com/Picovoice/rhino/files/7956436/MockUp.VBH.VoCo.3.zip)
